export const ICON_OPTIONS = [
  { name: "run", label: "Correr" },
  { name: "swim", label: "Nadar" },
  { name: "dumbbell", label: "Treinar" },
  { name: "book-open", label: "Ler" },
  { name: "school", label: "Estudar" },
  { name: "yoga", label: "Yoga" },
  { name: "meditation", label: "Meditar" },
  { name: "water", label: "Beber água" },
  { name: "food-apple", label: "Nutrição" },
  { name: "sleep", label: "Dormir" },
  { name: "guitar", label: "Música" },
  { name: "palette", label: "Arte" },
  { name: "code-tags", label: "Programar" },
  { name: "language", label: "Idiomas" },
  { name: "camera", label: "Fotografia" },
  { name: "walk", label: "Caminhar" },
  { name: "bike", label: "Pedalar" },
  { name: "basketball", label: "Esportes" },
  { name: "notebook", label: "Escrever" },
  { name: "brain", label: "Pensar" },
];
